// Package shellintegration prepares the user's shell to emit OSC 133
// semantic-prompt marks and OSC 7 cwd reports, by generating an rcfile
// (bash) or ZDOTDIR (zsh) that sources the user's own config first and the
// aish snippet after.
package shellintegration

import (
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
)

//go:embed snippets/aish.bash
var bashSnippet string

//go:embed snippets/aish.zsh
var zshSnippet string

// Setup returns the argv and extra environment to launch the given shell
// with aish integration. It writes generated files under dir (the session
// runtime dir). Unsupported shells run unmodified — the session still works,
// falling back to sentinel/idle framing.
func Setup(shell string, dir string) (argv []string, extraEnv []string, err error) {
	switch filepath.Base(shell) {
	case "bash":
		rc := filepath.Join(dir, "bashrc")
		content := "# generated by aish; sources your ~/.bashrc first\n" +
			"[ -f ~/.bashrc ] && . ~/.bashrc\n\n" + bashSnippet
		if err := os.WriteFile(rc, []byte(content), 0o600); err != nil {
			return nil, nil, fmt.Errorf("writing bash rcfile: %w", err)
		}
		return []string{shell, "--rcfile", rc}, nil, nil

	case "zsh":
		zdot := filepath.Join(dir, "zdotdir")
		if err := os.MkdirAll(zdot, 0o700); err != nil {
			return nil, nil, err
		}
		userZdot := os.Getenv("ZDOTDIR")
		if userZdot == "" {
			userZdot = "$HOME"
		}
		content := "# generated by aish; sources your own zshrc first\n" +
			"AISH_USER_ZDOTDIR=" + userZdot + "\n" +
			"[[ -f $AISH_USER_ZDOTDIR/.zshrc ]] && ZDOTDIR=$AISH_USER_ZDOTDIR source $AISH_USER_ZDOTDIR/.zshrc\n" +
			"ZDOTDIR=$AISH_USER_ZDOTDIR\n\n" + zshSnippet
		if err := os.WriteFile(filepath.Join(zdot, ".zshrc"), []byte(content), 0o600); err != nil {
			return nil, nil, fmt.Errorf("writing zsh rcfile: %w", err)
		}
		return []string{shell}, []string{"ZDOTDIR=" + zdot}, nil

	default:
		return []string{shell}, nil, nil
	}
}
